import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import localfont from "next/font/local";
import Footer from "@/components/Footer";

const solaimanLipi = localfont({
  src: [
    {
      path: "../../public/fonts/solaimanlipi.ttf"
    }
  ],
  variable: "--solaiman-lipi"
})

export const metadata = {
  title: "অগ্রসর | বিডি নিউজ | বাংলা নিউজ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={solaimanLipi.variable}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
